# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm i
    - run: |
        touch .env
        echo DATABASE_URL=${{ secrets.DATABASE_URL }} >> .env
        echo PORT=${{ secrets.PORT }} >> .env
        echo NOREPLY_EMAIL_ADDRESS=${{ secrets.NOREPLY_EMAIL_ADDRESS }} >> .env
        echo NOREPLY_EMAIL_PASSWORD=${{ secrets.NOREPLY_EMAIL_PASSWORD }} >> .env
        echo BASE_URL=${{ secrets.BASE_URL }} >> .env
        echo WEB_APP_URL=${{ secrets.WEB_APP_URL }} >> .env
        cat .env
    - run: npm run build --if-present
    - run: npx prisma generate
    - run: npx prisma migrate
    - run: npm ci
  
   
